import type { BlogPost } from './portfolio-data'

// Generated by scripts/fetch-medium-blogs.mjs. Edit the fetch script, not this file.
export const mediumBlogs: BlogPost[] = [
  {
    "title": "A 7-Billion-Parameter Conductor Just Claimed Frontier Performance. This is AI Orchestration.",
    "description": "Sakana AI\u2019s Fugu doesn\u2019t try to be smarter than GPT-5.5 or Mythos. It tries to be a better manager of them. That\u2019s either a gimmick or the next architecture \u2014 and the answer matte...",
    "url": "https://medium.com/@jainachal38/a-7-billion-parameter-conductor-just-claimed-frontier-performance-this-is-ai-orchestration-a0d4fe0102eb?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/max/1024/1*aqTQjC4ZkrlGOsgGh1CARg.png",
    "category": "ARTIFICIAL INTELLIGENCE",
    "date": "June 2026",
    "readTime": "7 min read",
    "featured": true,
    "tags": [
      "Artificial Intelligence",
      "AI Agent",
      "Llm",
      "Software Engineering"
    ]
  },
  {
    "title": "The Model Is Not Your Product. The Harness Is.",
    "description": "Harness engineering, and why it is becoming the most underrated skill in tech. Two teams. Same problem. Same model. Same Anthropic or OpenAI API key. Same documentation. The same...",
    "url": "https://pub.towardsai.net/the-model-is-not-your-product-the-harness-is-025984216741?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/max/1024/1*A-nqqozGwFncRDM-1tKS2g.png",
    "category": "WRITING PROMPTS",
    "date": "May 2026",
    "readTime": "7 min read",
    "featured": false,
    "tags": [
      "Writing Prompts",
      "Software Engineering",
      "Generative AI Tools",
      "Artificial Intelligence"
    ]
  },
  {
    "title": "The System Design Behind India\u2019s Most Stressful 60 Seconds \u2014 IRCTC Tatkal Booking",
    "description": "A billion-dollar engineering problem hiding in plain sight Every morning at 10:00 AM, something remarkable happens across India. Millions of people refresh the IRCTC website at th...",
    "url": "https://medium.com/towards-data-engineering/the-system-design-behind-indias-most-stressful-60-seconds-irctc-tatkal-booking-f30b02653a9a?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/max/1024/1*SdOYEJ1pZhVmWRJDYgDGTQ.png",
    "category": "TECHNOLOGY",
    "date": "April 2026",
    "readTime": "8 min read",
    "featured": false,
    "tags": [
      "Technology",
      "Backend Development",
      "System Design Concepts",
      "Software Engineering"
    ]
  },
  {
    "title": "If AI is Writing the Code, What\u2019s Left for Us?",
    "description": "A real look at where developers, CS students, and the job market are heading Let me say the thing everyone is thinking but nobody wants to say: it feels scary right now. If you ar...",
    "url": "https://pub.towardsai.net/if-ai-is-writing-the-code-whats-left-for-us-de4918b12434?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/proxy/1*O0dsyeTayhyDQF9eN0-njg.png",
    "category": "SOFTWARE ENGINEERING",
    "date": "April 2026",
    "readTime": "8 min read",
    "featured": false,
    "tags": [
      "Software Engineering",
      "Software Development",
      "Artificial Intelligence",
      "Technology"
    ]
  },
  {
    "title": "I Deployed a Stock Prediction Model on AWS \u2014 Here\u2019s Exactly How",
    "description": "Part 3 of the series: Running ML Projects on the Cloud Colab disconnected on me mid-training again. Kaggle hit the weekly limit on a Thursday. At some point you just want a server...",
    "url": "https://medium.com/towards-data-engineering/i-deployed-a-stock-prediction-model-on-aws-heres-exactly-how-6dfc7f4c918c?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/max/1024/1*TDRR60ZfUqe3XqP1aycd3Q.png",
    "category": "FASTAPI",
    "date": "April 2026",
    "readTime": "6 min read",
    "featured": false,
    "tags": [
      "FastAPI",
      "Machine Learning",
      "Cloud Computing",
      "Python"
    ]
  },
  {
    "title": "The AI Arms Race Has Already Begun \u2014 And No One Is Ready",
    "description": "The Pentagon\u2019s $13.4 billion military AI budget. China\u2019s autonomous drone swarms. Russia\u2019s combat-tested AI weapons. A cyber warfare revolution powered by deepfakes. Here\u2019s everyt...",
    "url": "https://medium.com/@jainachal38/the-ai-arms-race-has-already-begun-and-no-one-is-ready-fcae437cabbe?source=rss-f9caab75c17f------2",
    "platform": "medium",
    "image": "https://cdn-images-1.medium.com/proxy/1*NN90SU2q_Zrvqzj9b-aXNA.png",
    "category": "FUTURE OF WARFARE",
    "date": "March 2026",
    "readTime": "7 min read",
    "featured": false,
    "tags": [
      "Future Of Warfare",
      "Cybersecurity",
      "Geopolitics",
      "AI"
    ]
  }
]
